import { useParams, Navigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { WikiSidebar } from './WikiSidebar';
import { MarkdownRenderer } from './MarkdownRenderer';
import type { DocItem } from './wikiConfig';
import { Loader2 } from 'lucide-react';

/**
 * Fetches the docs manifest (auto-generated by sync-docs.mjs)
 */
async function fetchManifest(): Promise<DocItem[]> {
    const response = await fetch('/docs/docs-manifest.json');
    if (!response.ok) {
        throw new Error('Failed to load documentation manifest');
    }
    return response.json();
}

/**
 * Fetches markdown content from the docs directory.
 */
async function fetchMarkdown(path: string): Promise<string> {
    const response = await fetch(path);
    if (!response.ok) {
        throw new Error(`Failed to load document: ${response.statusText}`);
    }
    return response.text();
}

/**
 * Find a doc item by slug (searches nested children)
 */
function findDocBySlug(docs: DocItem[], slug: string): DocItem | undefined {
    for (const doc of docs) {
        if (doc.slug === slug) return doc;
        if (doc.children) {
            const child = findDocBySlug(doc.children, slug);
            if (child) return child;
        }
    }
    return undefined;
}

export function WikiPage() {
    const { '*': slug } = useParams();

    // Fetch manifest
    const { data: docs = [], isLoading: isLoadingManifest, error: manifestError } = useQuery({
        queryKey: ['wiki-manifest'],
        queryFn: fetchManifest,
        staleTime: 5 * 60 * 1000,
    });

    // Default to first doc if no slug
    const currentSlug = slug || docs[0]?.slug || 'home';
    const docItem = findDocBySlug(docs, currentSlug);

    const { data: content, isLoading: isLoadingContent, error: contentError } = useQuery({
        queryKey: ['wiki-doc', docItem?.path],
        queryFn: () => fetchMarkdown(docItem!.path!),
        enabled: !!docItem?.path,
        staleTime: 5 * 60 * 1000,
    });

    // Redirect to first doc if invalid slug and docs loaded (after all hooks)
    if (!docItem && slug && docs.length > 0) {
        return <Navigate to={`/wiki/${docs[0]?.slug}`} replace />;
    }

    if (isLoadingManifest) {
        return (
            <div className="flex items-center justify-center h-[calc(100vh-64px)]">
                <Loader2 className="w-8 h-8 animate-spin text-gray-400" />
            </div>
        );
    }

    if (manifestError) {
        return (
            <div className="flex items-center justify-center h-[calc(100vh-64px)]">
                <div className="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
                    <p className="text-red-600 font-medium">Failed to load documentation</p>
                    <p className="text-red-500 text-sm mt-1">
                        {manifestError instanceof Error ? manifestError.message : 'Unknown error'}
                    </p>
                </div>
            </div>
        );
    }

    return (
        <div className="flex h-[calc(100vh-64px)] -m-6">
            {/* Sidebar */}
            <WikiSidebar docs={docs} currentSlug={currentSlug} />

            {/* Content Area */}
            <main className="flex-1 overflow-y-auto bg-white">
                <div className="max-w-4xl mx-auto py-8 px-8">
                    {isLoadingContent && (
                        <div className="flex items-center justify-center py-20">
                            <Loader2 className="w-8 h-8 animate-spin text-gray-400" />
                        </div>
                    )}

                    {contentError && (
                        <div className="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
                            <p className="text-red-600 font-medium">Failed to load document</p>
                            <p className="text-red-500 text-sm mt-1">
                                {contentError instanceof Error ? contentError.message : 'Unknown error'}
                            </p>
                        </div>
                    )}

                    {!docItem?.path && docItem?.children && (
                        <div className="prose prose-slate max-w-none">
                            <h1 className="text-3xl font-bold text-gray-900 border-b pb-2 mb-4">
                                {docItem.title}
                            </h1>
                            <p className="text-gray-600">Select a topic from the sidebar to view documentation.</p>
                            <ul className="mt-4">
                                {docItem.children.map(child => (
                                    <li key={child.slug}>
                                        <a href={`/wiki/${child.slug}`} className="text-blue-600 hover:underline">
                                            {child.title}
                                        </a>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    )}

                    {content && <MarkdownRenderer content={content} />}
                </div>
            </main>
        </div>
    );
}
